"""Rename utility companies to utility providers

Revision ID: 3da74c02733e
Revises: 9db5a22952a6
Create Date: 2025-12-01 09:59:35.782521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3da74c02733e'
down_revision: Union[str, Sequence[str], None] = '9db5a22952a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('utility_companies', 'utility_providers')
    op.add_column('accounts', sa.Column('utility_provider_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_accounts_utility_company_id_utility_companies'), 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_accounts_utility_provider_id_utility_providers'), 'accounts', 'utility_providers', ['utility_provider_id'], ['id'])
    op.drop_column('accounts', 'utility_company_id')
    op.add_column('readings', sa.Column('utility_provider_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('readings_utility_company_id_fkey'), 'readings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_readings_utility_provider_id_utility_providers'), 'readings', 'utility_providers', ['utility_provider_id'], ['id'])
    op.drop_column('readings', 'utility_company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('utility_providers', 'utility_companies')
    op.add_column('readings', sa.Column('utility_company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_readings_utility_provider_id_utility_providers'), 'readings', type_='foreignkey')
    op.create_foreign_key(op.f('readings_utility_company_id_fkey'), 'readings', 'utility_companies', ['utility_company_id'], ['id'])
    op.drop_column('readings', 'utility_provider_id')
    op.add_column('accounts', sa.Column('utility_company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_accounts_utility_provider_id_utility_providers'), 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_accounts_utility_company_id_utility_companies'), 'accounts', 'utility_companies', ['utility_company_id'], ['id'])
    op.drop_column('accounts', 'utility_provider_id')
    op.drop_table('utility_providers')
    # ### end Alembic commands ###
