"""add account model

Revision ID: 9db5a22952a6
Revises: 42ba27f755d6
Create Date: 2025-11-28 08:24:21.744852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db5a22952a6'
down_revision: Union[str, Sequence[str], None] = '42ba27f755d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('utility_company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
    sa.ForeignKeyConstraint(['utility_company_id'], ['utility_companies.id'], name=op.f('fk_accounts_utility_company_id_utility_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.add_column('auth_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('auth_tokens', 'access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_auth_tokens_user_id_users'), 'auth_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('auth_tokens', 'refresh_token')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_telegram_id'), 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_telegram_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('auth_tokens', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_auth_tokens_user_id_users'), 'auth_tokens', type_='foreignkey')
    op.alter_column('auth_tokens', 'access_token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('auth_tokens', 'user_id')
    op.drop_table('accounts')
    # ### end Alembic commands ###
